#!/bin/bash

# REPOSITORY_NAME=$1

# REPOSITORY_TAG=${DOCKERHUB_USERNAME}/${ORGANIZATION_NAME}-$REPOSITORY_NAME:${BUILD_NUMBER}

# docker image build -t ${REPOSITORY_TAG} .
# docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
